// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"context"

	"github.com/nekr0z/gk/internal/server/secret"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// DeleteSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) DeleteSecret(context1 context.Context, s string, s1 string, bytes [32]byte) error {
	ret := _mock.Called(context1, s, s1, bytes)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, [32]byte) error); ok {
		r0 = returnFunc(context1, s, s1, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockSecretService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - bytes [32]byte
func (_e *MockSecretService_Expecter) DeleteSecret(context1 interface{}, s interface{}, s1 interface{}, bytes interface{}) *MockSecretService_DeleteSecret_Call {
	return &MockSecretService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", context1, s, s1, bytes)}
}

func (_c *MockSecretService_DeleteSecret_Call) Run(run func(context1 context.Context, s string, s1 string, bytes [32]byte)) *MockSecretService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 [32]byte
		if args[3] != nil {
			arg3 = args[3].([32]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) Return(err error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, bytes [32]byte) error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) GetSecret(context1 context.Context, s string, s1 string) (secret.Secret, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 secret.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (secret.Secret, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) secret.Secret); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(secret.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockSecretService_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockSecretService_Expecter) GetSecret(context1 interface{}, s interface{}, s1 interface{}) *MockSecretService_GetSecret_Call {
	return &MockSecretService_GetSecret_Call{Call: _e.mock.On("GetSecret", context1, s, s1)}
}

func (_c *MockSecretService_GetSecret_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockSecretService_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretService_GetSecret_Call) Return(secret1 secret.Secret, err error) *MockSecretService_GetSecret_Call {
	_c.Call.Return(secret1, err)
	return _c
}

func (_c *MockSecretService_GetSecret_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (secret.Secret, error)) *MockSecretService_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type MockSecretService
func (_mock *MockSecretService) ListSecrets(context1 context.Context, s string) ([]secret.Secret, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []secret.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]secret.Secret, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []secret.Secret); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]secret.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockSecretService_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockSecretService_Expecter) ListSecrets(context1 interface{}, s interface{}) *MockSecretService_ListSecrets_Call {
	return &MockSecretService_ListSecrets_Call{Call: _e.mock.On("ListSecrets", context1, s)}
}

func (_c *MockSecretService_ListSecrets_Call) Run(run func(context1 context.Context, s string)) *MockSecretService_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) Return(secrets []secret.Secret, err error) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) RunAndReturn(run func(context1 context.Context, s string) ([]secret.Secret, error)) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// PutSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) PutSecret(context1 context.Context, s string, secret1 secret.Secret, bytes [32]byte) error {
	ret := _mock.Called(context1, s, secret1, bytes)

	if len(ret) == 0 {
		panic("no return value specified for PutSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, secret.Secret, [32]byte) error); ok {
		r0 = returnFunc(context1, s, secret1, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretService_PutSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSecret'
type MockSecretService_PutSecret_Call struct {
	*mock.Call
}

// PutSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - secret1 secret.Secret
//   - bytes [32]byte
func (_e *MockSecretService_Expecter) PutSecret(context1 interface{}, s interface{}, secret1 interface{}, bytes interface{}) *MockSecretService_PutSecret_Call {
	return &MockSecretService_PutSecret_Call{Call: _e.mock.On("PutSecret", context1, s, secret1, bytes)}
}

func (_c *MockSecretService_PutSecret_Call) Run(run func(context1 context.Context, s string, secret1 secret.Secret, bytes [32]byte)) *MockSecretService_PutSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 secret.Secret
		if args[2] != nil {
			arg2 = args[2].(secret.Secret)
		}
		var arg3 [32]byte
		if args[3] != nil {
			arg3 = args[3].([32]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretService_PutSecret_Call) Return(err error) *MockSecretService_PutSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretService_PutSecret_Call) RunAndReturn(run func(context1 context.Context, s string, secret1 secret.Secret, bytes [32]byte) error) *MockSecretService_PutSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateToken(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockUserService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserService_Expecter) CreateToken(ctx interface{}, username interface{}, password interface{}) *MockUserService_CreateToken_Call {
	return &MockUserService_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, username, password)}
}

func (_c *MockUserService_CreateToken_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_CreateToken_Call) Return(s string, err error) *MockUserService_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_CreateToken_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockUserService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, username string, password string) error {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserService_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(err error) *MockUserService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) error) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockUserService
func (_mock *MockUserService) VerifyToken(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockUserService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserService_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockUserService_VerifyToken_Call {
	return &MockUserService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockUserService_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockUserService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_VerifyToken_Call) Return(s string, err error) *MockUserService_VerifyToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockUserService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
