// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/secret.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHashesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []*KeyHash             `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHashesResponse) Reset() {
	*x = ListHashesResponse{}
	mi := &file_api_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashesResponse) ProtoMessage() {}

func (x *ListHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashesResponse.ProtoReflect.Descriptor instead.
func (*ListHashesResponse) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{0}
}

func (x *ListHashesResponse) GetHashes() []*KeyHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type KeyHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHash) Reset() {
	*x = KeyHash{}
	mi := &file_api_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHash) ProtoMessage() {}

func (x *KeyHash) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHash.ProtoReflect.Descriptor instead.
func (*KeyHash) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{1}
}

func (x *KeyHash) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSecretResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type PutSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	KnownHash     []byte                 `protobuf:"bytes,3,opt,name=known_hash,json=knownHash,proto3" json:"known_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSecretRequest) Reset() {
	*x = PutSecretRequest{}
	mi := &file_api_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSecretRequest) ProtoMessage() {}

func (x *PutSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSecretRequest.ProtoReflect.Descriptor instead.
func (*PutSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{4}
}

func (x *PutSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutSecretRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutSecretRequest) GetKnownHash() []byte {
	if x != nil {
		return x.KnownHash
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	KnownHash     []byte                 `protobuf:"bytes,2,opt,name=known_hash,json=knownHash,proto3" json:"known_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secret_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteSecretRequest) GetKnownHash() []byte {
	if x != nil {
		return x.KnownHash
	}
	return nil
}

var File_api_secret_proto protoreflect.FileDescriptor

const file_api_secret_proto_rawDesc = "" +
	"\n" +
	"\x10api/secret.proto\x12\x02gk\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\x12ListHashesResponse\x12#\n" +
	"\x06hashes\x18\x01 \x03(\v2\v.gk.KeyHashR\x06hashes\"/\n" +
	"\aKeyHash\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"$\n" +
	"\x10GetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\x11GetSecretResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"W\n" +
	"\x10PutSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"known_hash\x18\x03 \x01(\fR\tknownHash\"F\n" +
	"\x13DeleteSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"known_hash\x18\x02 \x01(\fR\tknownHash2\x83\x02\n" +
	"\rSecretService\x12<\n" +
	"\n" +
	"ListHashes\x12\x16.google.protobuf.Empty\x1a\x16.gk.ListHashesResponse\x128\n" +
	"\tGetSecret\x12\x14.gk.GetSecretRequest\x1a\x15.gk.GetSecretResponse\x129\n" +
	"\tPutSecret\x12\x14.gk.PutSecretRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\fDeleteSecret\x12\x17.gk.DeleteSecretRequest\x1a\x16.google.protobuf.EmptyB\bZ\x06pkg/pbb\x06proto3"

var (
	file_api_secret_proto_rawDescOnce sync.Once
	file_api_secret_proto_rawDescData []byte
)

func file_api_secret_proto_rawDescGZIP() []byte {
	file_api_secret_proto_rawDescOnce.Do(func() {
		file_api_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_secret_proto_rawDesc), len(file_api_secret_proto_rawDesc)))
	})
	return file_api_secret_proto_rawDescData
}

var file_api_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_secret_proto_goTypes = []any{
	(*ListHashesResponse)(nil),  // 0: gk.ListHashesResponse
	(*KeyHash)(nil),             // 1: gk.KeyHash
	(*GetSecretRequest)(nil),    // 2: gk.GetSecretRequest
	(*GetSecretResponse)(nil),   // 3: gk.GetSecretResponse
	(*PutSecretRequest)(nil),    // 4: gk.PutSecretRequest
	(*DeleteSecretRequest)(nil), // 5: gk.DeleteSecretRequest
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_api_secret_proto_depIdxs = []int32{
	1, // 0: gk.ListHashesResponse.hashes:type_name -> gk.KeyHash
	6, // 1: gk.SecretService.ListHashes:input_type -> google.protobuf.Empty
	2, // 2: gk.SecretService.GetSecret:input_type -> gk.GetSecretRequest
	4, // 3: gk.SecretService.PutSecret:input_type -> gk.PutSecretRequest
	5, // 4: gk.SecretService.DeleteSecret:input_type -> gk.DeleteSecretRequest
	0, // 5: gk.SecretService.ListHashes:output_type -> gk.ListHashesResponse
	3, // 6: gk.SecretService.GetSecret:output_type -> gk.GetSecretResponse
	6, // 7: gk.SecretService.PutSecret:output_type -> google.protobuf.Empty
	6, // 8: gk.SecretService.DeleteSecret:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_secret_proto_init() }
func file_api_secret_proto_init() {
	if File_api_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_secret_proto_rawDesc), len(file_api_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_secret_proto_goTypes,
		DependencyIndexes: file_api_secret_proto_depIdxs,
		MessageInfos:      file_api_secret_proto_msgTypes,
	}.Build()
	File_api_secret_proto = out.File
	file_api_secret_proto_goTypes = nil
	file_api_secret_proto_depIdxs = nil
}
