// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) AddUser(ctx context.Context, user *User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStorage_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockUserStorage_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockUserStorage_Expecter) AddUser(ctx interface{}, user interface{}) *MockUserStorage_AddUser_Call {
	return &MockUserStorage_AddUser_Call{Call: _e.mock.On("AddUser", ctx, user)}
}

func (_c *MockUserStorage_AddUser_Call) Run(run func(ctx context.Context, user *User)) *MockUserStorage_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStorage_AddUser_Call) Return(err error) *MockUserStorage_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStorage_AddUser_Call) RunAndReturn(run func(ctx context.Context, user *User) error) *MockUserStorage_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) GetUser(ctx context.Context, username string) (*User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStorage_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserStorage_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserStorage_Expecter) GetUser(ctx interface{}, username interface{}) *MockUserStorage_GetUser_Call {
	return &MockUserStorage_GetUser_Call{Call: _e.mock.On("GetUser", ctx, username)}
}

func (_c *MockUserStorage_GetUser_Call) Run(run func(ctx context.Context, username string)) *MockUserStorage_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStorage_GetUser_Call) Return(user *User, err error) *MockUserStorage_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStorage_GetUser_Call) RunAndReturn(run func(ctx context.Context, username string) (*User, error)) *MockUserStorage_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
